version: '2'
services:
  # gobgp:
  #   build: ./gobgp
  #   ports:
  #     - 179:179
  #   volumes:
  #     - .:/var/tmp
  #   restart: always
  bgpdump:
    build: ./bgpdump
    volumes:
      - .:/var/tmp
    restart: always

  mongodb:
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - ./db:/data/db

  flask:
    build: ./flask
    ports:
      - 80:80
    volumes:
      - ./flask/app:/var/www/app
      - ./flask/app/log:/var/log/uwsgi/app
